################################################################################
# CONFIGURAÇÃO DO SERVIÇO DE NOTIFICAÇÃO
# @service notification-service
# @description Responsável por consumir eventos do RabbitMQ e disparar e-mails via SMTP.
# @author Erick Calazães
# @since 24/03/2026
################################################################################

# Identificação da aplicação no ecossistema de microserviços
spring.application.name=notification-service

# Porta de execução (Diferenciada para evitar conflito com o Scheduling Service)
server.port=8082

#-------------------------------------------------------------------------------
# CONFIGURAÇÕES DE MENSAGERIA (RABBITMQ)
# Conexão com o broker para consumo de eventos de agendamento.
#-------------------------------------------------------------------------------
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

#-------------------------------------------------------------------------------
# CONFIGURAÇÕES DE E-MAIL (MAILTRAP - AMBIENTE DE DEV)
# Protocolo SMTP para envio de notificações aos pacientes e médicos.
#-------------------------------------------------------------------------------
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=1b4f234594d5cb
spring.mail.password=0d30b22f976466
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#-------------------------------------------------------------------------------
# PERSISTÊNCIA DE DADOS (POSTGRESQL)
# Utilizado para auditoria e histórico de disparos de notificações.
#-------------------------------------------------------------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/notification_db
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate/JPA
# update: Atualiza o schema automaticamente sem apagar dados existentes.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true